stages:
  - install
  - lint
  - build
  - test

variables:
  NODE_VERSION: "16"
  CACHE_DIR: "redmcp-typescript/node_modules"

# Cache npm dependencies between jobs
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - $CACHE_DIR

# Install dependencies
install:
  stage: install
  image: node:$NODE_VERSION
  script:
    - cd redmcp-typescript
    - npm ci
    - npm install yaml
    - npm install --save-dev @types/jest
  artifacts:
    paths:
      - $CACHE_DIR
    expire_in: 1 day

# Run linting
lint:
  stage: lint
  image: node:$NODE_VERSION
  script:
    - cd redmcp-typescript
    - npm run lint || echo "Linting issues found, but continuing build"
  dependencies:
    - install
  allow_failure: true

# Build the project
build:
  stage: build
  image: node:$NODE_VERSION
  script:
    - cd redmcp-typescript
    - npm run build
  dependencies:
    - install
  artifacts:
    paths:
      - redmcp-typescript/build/
    expire_in: 1 day

# Run tests
test:
  stage: test
  image: node:$NODE_VERSION
  script:
    - cd redmcp-typescript
    - npm test
  dependencies:
    - build
    - install

# Test subproject creation specifically
test:subproject-creation:
  stage: test
  image: node:$NODE_VERSION
  script:
    - cd redmcp-typescript
    - npm i -g ts-node
    - cp -r ../fixes/subproject-test.ts ./src/tests/
    - ts-node src/tests/subproject-test.ts
  dependencies:
    - build
    - install
  allow_failure: true # Allow this to fail initially until the fix is properly implemented
  when: manual # This job is manually triggered for now
