version: '3.8'

services:
  redmine:
    environment:
      - RAILS_ENV=production
      - REDMINE_SECRET_KEY_BASE=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6
    volumes:
      - ./scripts/fix_redmine_config.sh:/docker-entrypoint-init.d/fix_redmine_config.sh
      
  mcp-extension:
    environment:
      - REDMINE_URL=http://redmine:3000
