version: '3.8'

services:
  mcp-extension:
    build: .
    container_name: mcp-extension-local
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - ./credentials.yaml:/app/credentials.yaml
    environment:
      - FLASK_DEBUG=1
      - REDMINE_URL=http://localhost:3000
      - DATABASE_URL=sqlite:////app/mcp.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health", "||", "exit", "0"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  redmine-mcp-network:
    driver: bridge

volumes:
  redmine-files:
    name: redmine-local-files
  redmine-sqlite:
    name: redmine-local-sqlite
