name: Claude API Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'llm_api.py'
      - 'scripts/test_claude_api.py'
      - '.github/workflows/claude-api-test.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'llm_api.py'
      - 'scripts/test_claude_api.py'
      - '.github/workflows/claude-api-test.yml'
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

jobs:
  test-claude-api:
    runs-on: ubuntu-latest
    
    env:
      CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml pytest pytest-cov
        
    - name: Set up environment
      run: |
        if [ -f scripts/setup_ci_environment.sh ]; then
          chmod +x scripts/setup_ci_environment.sh
          ./scripts/setup_ci_environment.sh
        else
          # Create a basic credentials file for testing
          echo "Creating basic credentials.yaml for testing..."
          cat > credentials.yaml << EOF
        redmine:
          url: http://localhost:3000
          api_key: test_api_key
        
        claude:
          api_key: $CLAUDE_API_KEY
        
        rate_limit: 100
        EOF
        fi
        
    - name: Run Claude API test
      run: |
        if [ -z "$CLAUDE_API_KEY" ]; then
          echo "::warning::CLAUDE_API_KEY is not set. Using mock mode for testing."
          python scripts/test_claude_api.py --mock
        else
          python scripts/test_claude_api.py --verbose
        fi
        
    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: claude-api-test-logs
        path: |
          logs/
          *.log
        retention-days: 7