name: Validate Configurations

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'pyproject.toml'
      - 'setup.py'
      - 'credentials.yaml.example'
      - 'docker-compose.yml'
      - 'docker-compose.local.yml'
      - 'scripts/validate_configs.py'
      - '.github/workflows/validate-configs.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'pyproject.toml'
      - 'setup.py'
      - 'credentials.yaml.example'
      - 'docker-compose.yml'
      - 'docker-compose.local.yml'
      - 'scripts/validate_configs.py'
      - '.github/workflows/validate-configs.yml'
  workflow_dispatch:

jobs:
  validate-configs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml tomli
        
    - name: Run configuration validator
      run: |
        python scripts/validate_configs.py
        
    - name: Check GitHub Actions workflows
      run: |
        if [ -f scripts/check_github_actions.sh ]; then
          chmod +x scripts/check_github_actions.sh
          ./scripts/check_github_actions.sh
        else
          echo "::warning::scripts/check_github_actions.sh not found. Skipping workflow checks."
        fi
        
    - name: Validate Docker Compose files
      run: |
        # Check docker-compose.yml
        if [ -f docker-compose.yml ]; then
          docker-compose -f docker-compose.yml config
          echo "✅ docker-compose.yml is valid"
        fi
        
        # Check docker-compose.local.yml
        if [ -f docker-compose.local.yml ]; then
          docker-compose -f docker-compose.local.yml config
          echo "✅ docker-compose.local.yml is valid"
        fi